broker: {
  name: "broker1",
  host: "127.0.0.1",
  port: 8889,
  defaultSendSize: 30,
  rpcTimeout: 5,
  loadWeight: {
    cpu: 1,
    memory: 1,
    bandwidthIn: 1,
    bandwidthOut: 1,
  },

  syncWrite2disk: true,
  asyncWriteMsglimit: 10,

  isLoadBalancerEnabled: true,
  collectLoadDataInterval: 5,
  pushLoadDataInterval: 6,

  defaultNumberOfBundles: 16,

  brokerDeduplicationEnabled: false,

  allowRenameForClient: true,

  operationRedoNum: 3,
  operationTimeout: 1,
}

zookeeper: {
  host: {

  },
  root: "/Xmq",
  brokerRoot: /"Xmq/broker",
  topicRoot: "/Xmq/topic",
  bundleRoot: "/Xmq/bundle",
  sessionTimeout: 3,
}

etcd: {
  Endpoints: {

  },
  DialTimeout: 3,
}