broker: {
  name: "broker1",
  host: "127.0.0.1",
  port: 8889,
  defaultSendSize: 30,
  rpcTimeout: 5,
  # load Weight
  cpuWeight: 1,
  virtualMemoryWeight: 1,
  swapMemoryWeight: 1,
  bandwidthInWeight: 1,
  bandwidthOutWeight: 1,

  # load Limit
  cpuLimit: 0.85,
  virtualMemoryLimit: 0.85,
  swapMemoryLimit: 0.85,
  bandwidthInLimit: ,
  bandwidthOutLimit: ,

  syncWrite2disk: true,
  asyncWriteMsglimit: 10,

  isLoadBalancerEnabled: true,
  collectLoadDataInterval: 5,
  pushLoadDataInterval: 6,

  defaultNumberOfBundles: 16,
  defaultMaxAddress: 16,

  brokerDeduplicationEnabled: false,

  allowRenameForClient: true,

  operationRedoNum: 3,
  operationTimeout: 1,
}

zookeeper: {
  host: ["127.0.0.1:2181"],
  root: "/Xmq",
  brokerRoot: /"Xmq/broker",
  topicRoot: "/Xmq/topic",
  bundleRoot: "/Xmq/bundle",
  sessionTimeout: 3,
}

etcd: {
  Endpoints: ["127.0.0.1:2379"],
  DialTimeout: 3,
}